### ISSUE TITLE
Amplitude Modulation? 

### ISSUE THREAD

**Issue by Astro-Adrian** [christian-hahn/windfreak-python#4]
Does this code support amplitude modulation with the synthHD V2 (not the pro).  I'm looking to apply an amplitude modulation to a signal while also varying the power of that signal.

**Comment by micooke** [comment]
It's open source, took me 1 minute to find your answer

https://github.com/christian-hahn/windfreak-python/blob/685f8af43de31567784d8e1f2ec58e550624ebf8/windfreak/synth_hd.py#L630
